### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by jskrepnek** [mjwheatley/cordova-plugin-android-fingerprint-auth#52] opened 2017-02-04 17:22 UTC
I can't reproduce this consistently.  It's usually when the app is launching after it's been backgrounded for a while.

I'm essentially using version 1.2.2 of the plugin.  So far only seen on Android 7.1, Nexus 5X (bullhead).

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{ca.koho/ca.koho.Koho}: android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:190)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2101)
	at android.content.res.Resources.getLayout(Resources.java:1115)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:424)
	at com.cordova.plugin.android.fingerprintauth.FingerprintAuthenticationDialogFragment.onCreateView(FingerprintAuthenticationDialogFragment.java:85)
	at android.app.Fragment.performCreateView(Fragment.java:2353)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2039)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:176)
	at android.app.Activity.performCreateCommon(Activity.java:6673)
	at android.app.Activity.performCreate(Activity.java:6681)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	... 9 more
```

**Comment by jeansantana** [comment] 2017-04-27 05:21
Same error here! Found some solution?

**Comment by mjwheatley** [comment] 2017-06-15 19:53
Hopefully this has been resolved with the fix to allow state loss in version 1.2.8
Closing this issue for now.  If it is still occurring please reopen the issue.

**Comment by SeeWhat** [comment] 2017-06-29 03:17
Got this exception again while using 1.3.0. Same stacktrace.

**Comment by jonathankau** [comment] 2017-08-03 17:37
+1 to what @SeeWhat said, although we're still on 1.2.8. We've seen about ~150 crashes on 7.0 Samsung Galaxy devices:

![screen shot 2017-08-03 at 10 37 07 am](https://user-images.githubusercontent.com/4529259/28934983-c43b2592-7837-11e7-86f1-314863da264f.png)

**Comment by Azamat-Nurzhanuly** [comment] 2017-08-15 10:15
First of all, thank you for this plugin. It's very usefull. 
We have the same problem on Redmi 4, Redmi Note 3, Redmi 4X using plugin version 1.3.1. Please, could you reopen this issue and answer when the problem will be resolved?
This is emergency situation.
Thank you in advance.

**Comment by mjwheatley** [comment] 2017-08-15 12:13
Very difficult to troubleshoot with the stack trace alone.  It has been mentioned that it cannot be reproduced consistent.  I can not reproduce the error so I can't debug the issue.  I do not have access to the devices mentioned for testing.  If you would like resolution to this issue please contribute by providing more helpful/useful information.

**Comment by Azamat-Nurzhanuly** [comment] 2017-09-15 09:36
@mjwheatley, I'm sorry for long answer. I had problems that demanded my immediate attention.

I can't reproduce it neither. I saw this from crash reporter in firebase console. I have only the stack trace. But it is the same as @jskrepnek wrote.

`Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{air.com.ssdsoftwaresolutions.clickuz/air.com.ssdsoftwaresolutions.clickuz.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2984)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3045)
android.app.ActivityThread.-wrap14 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1642)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6776)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1386)
arrow_drop_down
Caused by android.content.res.Resources$NotFoundException: Resource ID #0x0
android.content.res.ResourcesImpl.getValue (ResourcesImpl.java:202)
android.content.res.Resources.loadXmlResourceParser (Resources.java:2970)
android.content.res.Resources.getLayout (Resources.java:1986)
android.view.LayoutInflater.inflate (LayoutInflater.java:425)
com.cordova.plugin.android.fingerprintauth.FingerprintAuthenticationDialogFragment.onCreateView (FingerprintAuthenticationDialogFragment.java:85)
android.app.Fragment.performCreateView (Fragment.java:2352)
android.app.FragmentManagerImpl.moveToState (FragmentManager.java:995)
android.app.FragmentManagerImpl.moveToState (FragmentManager.java:1171)
android.app.FragmentManagerImpl.moveToState (FragmentManager.java:1153)
android.app.FragmentManagerImpl.dispatchActivityCreated (FragmentManager.java:2043)
android.app.FragmentController.dispatchActivityCreated (FragmentController.java:177)
android.app.Activity.performCreateCommon (Activity.java:6949)
android.app.Activity.performCreate (Activity.java:6957)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1126)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2927)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3045)
android.app.ActivityThread.-wrap14 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1642)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6776)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1386)`

**Comment by newuser44** [comment] 2017-10-17 17:49
Nothing new to add, but having the same issue with our apps.   Not sure what Samsung does differently with their phones.

**Comment by jskrepnek** [comment] 2017-10-17 18:51
We traced most (but not all) of these to the scenario where the fragment was displayed when the application was paused.  It our case it would usually happen when the power button was pressed.  Have a look at the changes: https://github.com/kohofinancial/cordova-plugin-android-fingerprint-auth/commits/master.

**Comment by newuser44** [comment] 2017-10-17 20:02
Thanks for the response.  I'm confused. We have version 1.31. of the plugin.   The fix should be in that version?  Not sure why we still get the crashes for samsung devices.

**Comment by jskrepnek** [comment] 2017-10-17 20:08
@newuser44 We forked the plugin - the fixes have not come back to the origin.  You'd have to look at the commits in our forked repo for details.

**Comment by videmort** [comment] 2018-03-23 01:06
Hi
Current status for this error?

**Comment by dickverweij** [comment] 2018-03-28 14:41
same here .. current status?

**Comment by mjwheatley** [comment] 2018-03-28 15:03
Same as my last post as no additional information has been provided to help troubleshoot the issue.

**Comment by dickverweij** [comment] 2018-03-28 15:18
What do you need? we have crash logs

**Comment by dickverweij** [comment] 2018-03-28 15:20
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2924)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2985)
  at android.app.ActivityThread.-wrap14 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1635)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6692)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
Caused by: android.content.res.Resources$NotFoundException: 
  at android.content.res.ResourcesImpl.getValue (ResourcesImpl.java:202)
  at android.content.res.Resources.loadXmlResourceParser (Resources.java:2968)
  at android.content.res.Resources.getLayout (Resources.java:1984)
  at android.view.LayoutInflater.inflate (LayoutInflater.java:425)
  at com.cordova.plugin.android.fingerprintauth.FingerprintAuthenticationDialogFragment.onCreateView (FingerprintAuthenticationDialogFragment.java:85)
  at android.app.Fragment.performCreateView (Fragment.java:2352)
  at android.app.FragmentManagerImpl.moveToState (FragmentManager.java:995)
  at android.app.FragmentManagerImpl.moveToState (FragmentManager.java:1171)
  at android.app.FragmentManagerImpl.moveToState (FragmentManager.java:1153)
  at android.app.FragmentManagerImpl.dispatchActivityCreated (FragmentManager.java:2043)
  at android.app.FragmentController.dispatchActivityCreated (FragmentController.java:177)
  at android.app.Activity.performCreateCommon (Activity.java:6906)
  at android.app.Activity.performCreate (Activity.java:6914)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1126)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2877)

**Comment by mjwheatley** [comment] 2018-03-28 18:14
Please provide steps to reproduce the issue on a simulator and the simulator config information.

**Comment by dickverweij** [comment] 2018-04-03 10:22
It only happens on 7.0 devices as far as i can see. Perhaps somethings to do with theme? I cant reproduce it yet in emulators.

**Comment by dickverweij** [comment] 2018-04-05 11:41
![image](https://user-images.githubusercontent.com/8133838/38363979-0bb53290-38d7-11e8-94fb-7e787ad3105c.png)

still more crashes every day..  (also on 8.0) ..

**Comment by mjwheatley** [comment] 2018-04-05 13:31
Have you tried what @jskrepnek mentioned and dismiss the dialog in onPause?

```
@Override
     public void onPause() {
         super.onPause();
+        // Dismiss dialog to avoid doubling it on resume if app was closed by OS
+        dismissAllowingStateLoss();
         mFingerprintUiHelper.stopListening();
     }	    
```

If we can't replicate the issue it will be difficult to determine if any changes resolve the issue.

**Comment by WuglyakBolgoink** [comment] 2018-08-09 11:15
same 

![image](https://user-images.githubusercontent.com/2271337/43895632-3fda5e26-9bd6-11e8-8b73-81e7d5f72674.png)

**Comment by danicholls** [comment] 2019-01-12 04:09
Any update on whether this worked? `dismiss` is out there, right?

**Comment by mjwheatley** [comment] 2019-01-12 05:24
Yes, the `dismiss()` method has been published.  No one experiencing this issue has commented whether or not they have implemented it or if it has had any impact.

**Comment by danicholls** [comment] 2019-02-01 05:05
Just noting that per [this](https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/pull/142), which is based off your work, and the reports [here](https://github.com/NiklasMerz/cordova-plugin-fingerprint-aio/issues/132), I think this is handled.

**Comment by mjwheatley** [comment] 2019-02-01 13:15
Thanks for the references.  I will go ahead and close this issue.

**Closed by mjwheatley** 2019-02-01 13:15 UTC
Labels: help wanted
