### ISSUE TITLE
There should be hide() function

### ISSUE THREAD

**Issue by razam217** [mjwheatley/cordova-plugin-android-fingerprint-auth#21] opened 2016-09-27 13:19 UTC
There should be a FingerprintAuth.hide() method to hide the dialog.

**Comment by mjwheatley** [comment] 2016-09-27 13:27
Please provide a use case.  Why would you need to hide the dialog?

**Comment by razam217** [comment] 2016-09-27 13:49
When I resume my app, it asks me for the touchID and I do not enter it also I do not cancel and directly move the app to background state. Now when I resume my app, it first shows error on touchID dialog i.e. 'Finger print not recognized try again.' and then opens another dialog without that error, but that does not respond when I try to enter touchID.

**Comment by mjwheatley** [comment] 2016-09-27 13:57
That would be an implementation error and not an issue with the plugin.  If your application goes into the background while the dialog is open, the expectation would be that the dialog would still be open when your application resumes.  The problem is that you are triggering the dialog to open in on resume, so your app is trying to open a second dialog, which is causing a problem.

You should set a flag in your app to indicate if the dialog has been open and save that state when your application goes to the background.  In on resume, if that flag indicates that the dialog is open, do not try to show another dialog.

**Comment by razam217** [comment] 2016-09-28 06:45
Thanks a lot, that really helped. It was an implementation error.

**Comment by lxAppDev** [comment] 2017-04-13 08:44
Following Use case:

- User opens App, Authentication dialog appears
- User closed app
- User disables Fingerprint or deletes all Fingerprints from the database
- User opens App, Authentication dialog is still visible

**Comment by mknauer** [comment] 2018-10-31 16:47
Can we re-open this issue somehow? And if necessary, we'd be happy to contribute a change...

Our use case is a bit complex. Imagine an app where _external_ events (e.g. push notifications) are controlling, which authentication methods (fingerprint or password) are permitted.

Let's assume a push notification arrives that allows using a fingerprint for authentication. The app opens and we show the fingerprint dialog, because that is what the incoming push notification tells us to do.

Unfortunately the user decides to ignore that, and triggers another event that again leads to opening the app. But this time, fingerprint is not permitted, the app unlock must only be possible by entering the password.
In this case, the fingerprint dialog is still showing up but should be closed...

Do you understand that there are thinkable use cases that can only be solved by programmatically closing the dialog?

**Comment by mjwheatley** [comment] 2018-10-31 18:54
Understood.  I have a local branch where I implemented the `hide()` method.  I will merge that branch and push a new version for you to test.

**Comment by mjwheatley** [comment] 2018-10-31 18:58
Actually I named it `dismiss()`

**Comment by mjwheatley** [comment] 2018-10-31 19:07
I have published version 1.5.0

**Closed by mjwheatley** 2018-10-31 19:07 UTC

**Comment by mknauer** [comment] 2018-10-31 19:56
Wow, I'm impressed! Thanks, we'll be testing the new version.
